openapi: 3.0.3
info:
  title: Flashcard API
  description: API for managing flashcards in a learning application
  version: 1.0.0
  contact:
    name: Support
    email: support@example.com
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /flashcards:
    get:
      summary: Get all flashcards
      description: Retrieves a list of all flashcards
      operationId: getFlashcards
      parameters:
        - name: category
          in: query
          description: Filter flashcards by category
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of flashcards
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flashcard'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Create a new flashcard
      description: Creates a new flashcard with the provided data
      operationId: createFlashcard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlashcardCreateRequest'
      responses:
        '201':
          description: Flashcard created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flashcard'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /flashcards/{id}:
    parameters:
      - name: id
        in: path
        description: ID of the flashcard
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: Get a specific flashcard
      description: Retrieves a flashcard by its ID
      operationId: getFlashcard
      responses:
        '200':
          description: Flashcard found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flashcard'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      summary: Update a flashcard
      description: Updates an existing flashcard with the provided data
      operationId: updateFlashcard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FlashcardUpdateRequest'
      responses:
        '200':
          description: Flashcard updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flashcard'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      summary: Delete a flashcard
      description: Deletes a flashcard by its ID
      operationId: deleteFlashcard
      responses:
        '204':
          description: Flashcard deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    Flashcard:
      type: object
      required:
        - id
        - front
        - back
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          format: int64
          example: 1
        front:
          type: string
          example: "What is the capital of France?"
        back:
          type: string
          example: "Paris"
        category:
          type: string
          example: "Geography"
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    FlashcardCreateRequest:
      type: object
      required:
        - front
        - back
      properties:
        front:
          type: string
          example: "What is the capital of France?"
        back:
          type: string
          example: "Paris"
        category:
          type: string
          example: "Geography"
    FlashcardUpdateRequest:
      type: object
      properties:
        front:
          type: string
          example: "What is the capital of France?"
        back:
          type: string
          example: "Paris"
        category:
          type: string
          example: "Geography"
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: "Error message"
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
